work/vagrant/meshiterro/config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/post_comments" => "post_comments#index"
  resources :post_images, only:[:new, :create, :index, :show, :destroy] do
  	resource :favorites, only:[:create, :destroy]
   resource :post_comments, only: [:create, :destroy]
end

	resources :users, only: [:show, :edit, :update]

end

work/vagrant/meshiterro/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

work/vagrant/meshiterro/app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :post_image

end

work/vagrant/meshiterro/app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :post_image

end

work/vagrant/meshiterro/app/models/post_image.rb
class PostImage < ApplicationRecord

	belongs_to :user
	attachment :image
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	validates :shop_name, presence: true
	validates :image, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

end

work/vagrant/meshiterro/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image

end

work/vagrant/meshiterro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :authenticate_user!
	before_action :configure_permitted_parameters,if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
		devise_parameter_sanitizer.permit(:account_update,keys: [:name,:profile_image])
	end
end

work/vagrant/meshiterro/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

        def create
            post_image = PostImage.find(params[:post_image_id])
            favorite = current_user.favorites.new(post_image_id: post_image.id)
            favorite.save
            redirect_to post_image_path(post_image)
        end
        def destroy
            post_image = PostImage.find(params[:post_image_id])
            favorite = current_user.favorites.find_by(post_image_id: post_image.id)
            favorite.destroy
            redirect_to post_image_path(post_image)
        end

end

work/vagrant/meshiterro/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def index
		@post_comments = Post_comment.all
	end

	def create
		post_image = PostImage.find(params[:post_image_id])
		comment = current_user.post_comments.new(post_comment_params)
		comment.post_image_id = post_image.id
		comment.save
		redirect_to post_image_path(post_image)
	end

	private

	def post_comment_params
		params.require(:post_comment).permit(:user_id, :post_image_id, :comment)
	end

end

work/vagrant/meshiterro/app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

	def about
	end

	def new
		@post_image = PostImage.new
	end

	def create
		@post_image = PostImage.new(post_image_params)
		@post_image.user_id = current_user.id
		if @post_image.save
			redirect_to post_images_path
		else
			render :new
		end
	end

	def index
		@post_images = PostImage.page(params[:page]).reverse_order
	end

	def show
		@post_image = PostImage.find(params[:id])
		@post_comment = PostComment.new
	end

	def destroy
		@post_image = PostImage.find(params[:id])
		@post_image.destroy
		redirect_to post_images_path
	end


	private
		def post_image_params
			params.require(:post_image).permit(:shop_name, :image, :caption)
		end

end

work/vagrant/meshiterro/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@post_images = @user.post_images.page(params[:page]).reverse_order
  end
  def edit
  	@user = User.find(params[:id])
  end
  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user.id)
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image)
  end
end

work/vagrant/meshiterro/app/helpers/application_helper.rb
module ApplicationHelper
end

work/vagrant/meshiterro/app/helpers/favorites_helper.rb
module FavoritesHelper
end

work/vagrant/meshiterro/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

work/vagrant/meshiterro/app/helpers/post_images_helper.rb
module PostImagesHelper
end

work/vagrant/meshiterro/app/helpers/users_helper.rb
module UsersHelper
end

work/vagrant/meshiterro/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meshiterro</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head> 

  <body>

    <div class="header" id="header">
      <nav class="navbar navbar-main navbar-shadow" role="navigation" id="slide-nav">
        <div class="container relative">
          <div class="navbar-header">
            <a class="navbar-logo" href="/">
              <%= image_tag('/images/logo.png') %>
            </a>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="slidemenu">
            <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
              <% if user_signed_in? %>
              <li class="">
                <%= link_to "ログアウト",destroy_user_session_path, method: :delete %>
              </li>
              <li class="">
                <%= link_to "投稿フォーム", new_post_image_path %>
              </li>
              <li class="">
                <%= link_to "マイページ", user_path(current_user.id) %>
              </li>
              <% else %>
	      	  	<li class="">
                <%= link_to "新規登録", new_user_registration_path %>
              </li>
              <li class="">
                <%= link_to "ログイン", new_user_session_path %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <%= yield %>

   <footer class="footer style-2">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="col">
              <br>
              <p class="no-margin" style="font-size: 11px;">
              <br>
              善良な市民同士で無差別に食欲を煽るSNS
          </p>
              <%= image_tag('/images/logo-white.png') %>
              
            </div>
          </div>
          <div class="col-md-2">
            <div class="col">
              <h4>Link</h4>
              <ul>
                <li>
                  <a href="" title="About">会社概要</a>
                </li>
                <li>
                  <a href="" title="License informations">プライバシーポリシー</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
</html>