work/vagrant/bookers4/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "top#index"
  get "top/about" => "top#about"
  get "books/books_page" => "books#books_page"
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update]

end

work/vagrant/bookers4/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

work/vagrant/bookers4/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :opinion, presence: true, length: { maximum: 200, too_long: "This is the error. Please enter within 200 characters"}



end

work/vagrant/bookers4/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: 2..20
  validates :plofile, length:{ maximum: 50, too_long: "This is the error. Please enter within 50 characters"}

  def email_required?
  	false
  end
  def email_changed?
  	false
  end

  attachment :profile_image

  has_many :books, dependent: :destroy
end

work/vagrant/bookers4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		books_path
	end

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
	end

end

work/vagrant/bookers4/app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			redirect_to book_path(@book.id), notice: "You create book successfully."
		else
			@books = current_user.books.all
			@profile_image = current_user
			render action: :index
		end
	end

	def index
		@book = Book.new
		@books = current_user.books.all
		@profile_image = current_user
	end

	def show
		@book = Book.new
		@books = Book.find(params[:id])
	end

	def destroy
		@book = Book.find(params[:id])
		if @book.destroy
		redirect_to books_path, notice: "You deleted book successfully."
		else
			render action: :index
		end
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user != current_user
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		redirect_to book_path, notice: "You update successfully."
		else
			render action: :edit
		end
	end

	def books_page
		@book = Book.new
		@books = Book.all
		@profile_image = current_user
	end

	private

		def book_params
			params.require(:book).permit(:user_id, :title, :opinion)
		end

end

work/vagrant/bookers4/app/controllers/top_controller.rb
class TopController < ApplicationController
	def index
	end
	def about
	end
end

work/vagrant/bookers4/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @book = Book.new
    @profile_image = current_user
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.all
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to books_path
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	 redirect_to books_path, notice: "You update successfully."
    else
      render action: :edit
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :plofile, :profile_image)
  end
end

work/vagrant/bookers4/app/helpers/application_helper.rb
module ApplicationHelper
end

work/vagrant/bookers4/app/helpers/books_helper.rb
module BooksHelper
end

work/vagrant/bookers4/app/helpers/top_helper.rb
module TopHelper
end

work/vagrant/bookers4/app/helpers/users_helper.rb
module UsersHelper
end

work/vagrant/bookers4/app/views/books/books_page.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<section class="">
				<h2>User info</h2>
				<table>
					<%= attachment_image_tag @profile_image, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
					<tr>
						<td><span class="text">name</span></td>
						<td><span class="text"><%= current_user.name %></span></td>
					</tr>
					<tr>
						<td><span class="text">introduction</span></td>
						<td><span class="text"><%= current_user.plofile %></span></td>
					</tr>
				</table>
				<%= link_to edit_user_path(current_user.id), class: "edit_user_#{current_user.id}" do %>
					<span class="glyphicon glyphicon-edit btn btn-default btn-block" aria-hidden="true"></span>
				<% end %>
				<h2>New Book</h2>
				<%= form_for(@book) do |f| %>
						<% if @book.errors.any? %>
							<h3><%= @book.errors.count %> errors have occurred</h3>
							<ul>
								<% @book.errors.full_messages.each do |message| %>
								<li><%= message %></li>
								<% end %>
							</ul>
						<% end %>
					<p>
						<strong>Title</strong><br>
						<%= f.text_field :title, class: "book_title" %>
					</p>
					<p>
						<strong>Opinion</strong><br>
						<%= f.text_area :opinion, class: "book_body" %>
					</p>
					<p>
						<%= f.submit "Create Book", class: "btn-default btn-sm btn-primary btn-block" %>
					</p>
				<% end %>
			</section>
		</div>
		<div class="col-sm-8">
			<section class="">
				<h2>Books</h2>
				<table class="sidebar">
					<tr>
						<td></td>
						<td><span class="text"><strong>Title</strong></span></td>
						<td><span class="text"><strong>Opinion</strong></span></td>
					</tr>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
						</td>
						<td>
							<%= link_to book_path(book.id), class: "book_#{book.id}" do %>
								<span class="text"><%= book.title %></span>
							<% end %>
						</td>
						<td><span class="text"><%= book.opinion %></span></td>
					</tr>
					<% end %>
				</table>
			</section>
		</div>
	</div>
</div>

work/vagrant/bookers4/app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h2>Editing Book</h2>
			<%= form_for(@book) do |f| %>
			<% if @book.errors.any? %>
				<h3><%= @book.errors.count %> errors have occurred</h3>
				<ul>
					<% @book.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			<% end %>
			<p>Title<br>
				<%= f.text_field :title, :size=>"100%x20", class: "book_title" %>
			</p>
			<p>Opinion<br>
				<%= f.text_area :opinion, :size=>"100%x5", class: "book_body" %>
			</p>
			<%= f.submit "Update Book", class: "btn-default btn-sm btn-primary btn-block" %>
			<% end %>
			<%= link_to "Show", book_path, class: "book_#{@book.id}" %> | 
			<%= link_to "Back", books_books_page_path, class: "book_#{@book.id}" %>
		</div>
	</div>
</div>

work/vagrant/bookers4/app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<section class="">
				<% if flash[:notice] %>
					<span class="text"><%= flash[:notice] %></span>
				<% end %>
				<h2>User info</h2>
				<table>
					<%= attachment_image_tag @profile_image, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
					<tr>
						<td><span class="text">name</span></td>
						<td><span class="text"><%= current_user.name %></span></td>
					</tr>
					<tr>
						<td><span class="text">introduction</span></td>
						<td><span class="text"><%= current_user.plofile %></span></td>
					</tr>
				</table>
				<%= link_to edit_user_path(current_user.id), class: "edit_user_#{current_user.id}" do %>
					<span class="glyphicon glyphicon-edit btn btn-default btn-block" aria-hidden="true"></span>
				<% end %>
				<h2>New Book</h2>
				<%= form_for(@book) do |f| %>
						<% if @book.errors.any? %>
							<h3><%= @book.errors.count %> errors have occurred</h3>
							<ul>
								<% @book.errors.full_messages.each do |message| %>
								<li><%= message %></li>
								<% end %>
							</ul>
						<% end %>
					<p>
						<strong>Title</strong><br>
						<%= f.text_field :title, class: "book_title" %>
					</p>
					<p>
						<strong>Opinion</strong><br>
						<%= f.text_area :opinion, class: "book_body" %>
					</p>
					<p>
						<%= f.submit "Create Book", class: "btn-default btn-sm btn-primary btn-block" %>
					</p>
				<% end %>
			</section>
		</div>
		<div class="col-sm-8">
			<section class="">
				<h2>Books</h2>
				<table class="sidebar">
					<tr>
						<td>画像</td>
						<td><strong>Title</strong></td>
						<td><strong>Opinion</strong></td>
					</tr>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= attachment_image_tag @profile_image, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
						</td>
						<td>
							<%= link_to book_path(book.id), class: "book_#{book.id}" do %>
								<span class="text"><%= book.title %></span>
							<% end %>
						</td>
						<td><span class="text"><%= book.opinion %></span></td>
					</tr>
					<% end %>
				</table>
			</section>
		</div>
	</div>
</div>

work/vagrant/bookers4/app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<section class="">
				<% if flash[:notice] %>
					<span class="text"><%= flash[:notice] %></span>
				<% end %>
				<h2>User info</h2>
				<table>
					<%= attachment_image_tag @books.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
					<tr>
						<td><span class="text">name</span></td>
						<td><span class="text"><%= @books.user.name %></span></td>
					</tr>
					<tr>
						<td><span class="text">introduction</span></td>
						<td><span class="text"><%= @books.user.plofile %></span></td>
					</tr>
				</table>
				<%= link_to edit_user_path(current_user.id), class: "edit_user_#{current_user.id}" do %>
					<span class="glyphicon glyphicon-edit btn btn-default btn-block" aria-hidden="true"></span>
				<% end %>
				<h2>New Book</h2>
				<%= form_for(@book) do |f| %>
						<% if @book.errors.any? %>
							<h3><%= @book.errors.count %> errors have occurred</h3>
							<ul>
								<% @book.errors.full_messages.each do |message| %>
								<li><%= message %></li>
								<% end %>
							</ul>
						<% end %>
					<p>
						<strong>Title</strong><br>
						<%= f.text_field :title, class: "book_title" %>
					</p>
					<p>
						<strong>Opinion</strong><br>
						<%= f.text_area :opinion, class: "book_body" %>
					</p>
					<p>
						<%= f.submit "Create Book", class: "btn-default btn-sm btn-primary btn-block" %>
					</p>
				<% end %>
			</section>
		</div>
		<div class="col-sm-8">
			<section class="">
				<h2>Book detail</h2>
				<table class="sidebar">
					<tr>
						<td>
							<%= link_to user_path(@books.user.id), class: "book_#{@books.user.id}" do %>
							<%= attachment_image_tag @books.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %><br>
							<%= @books.user.name %>
							<% end %>
						</td>
						<td><span class="text"><%= @books.title %></span></td>
						<td><span class="text"><%= @books.opinion %></span></td>
						<% if @books.user == current_user %>
						<td><%= link_to edit_book_path, class: "edit_book_#{@books.id}" do %>
								<span class="text btn btn-success btn-block">edit</span>
							<% end %>
						</td>
						<td>
							<%= link_to book_path, class: "destroy_book_#{@books.id}", method: :delete, "data-confirm" => "Are you sure?" do %>
								<span class="text btn btn-danger btn-block">destroy</span>
							<% end %>
						</td>
						<% end %>
					</tr>
				</table>
			</section>
		</div>
	</div>

work/vagrant/bookers4/app/views/top/about.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h2>Welcome to
			<span class="glyphicon glyphicon-book" aria-hidden="true"></span>
			Bookers!!</h2>
		</div>
	</div>
</div>

work/vagrant/bookers4/app/views/top/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

			<h1 class="jquery">Hello jQuery!</h1>

			<h2>Welcome to<br>
			<span class="glyphicon glyphicon-book" aria-hidden="true"></span>
			Bookers!!</h2>
			<p>In 
			<span class="glyphicon glyphicon-book" aria-hidden="true"></span>
			Bookers,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about various books!</p>

			<div>
				<%= link_to new_user_session_path do %>
				<button type="button" class="btn-default btn-sm btn-info btn-block">Log in</button>
				<% end %>
			</div>
			<div>
				<%= link_to new_user_registration_path do %>
				<button type="button" class="btn-default btn-sm btn-success btn-block">Sign up</button>
				<% end %>
			</div>
		</div>
	</div>
</div>